### ISSUE TITLE
Advantages to evafast

### ISSUE THREAD

**Issue by po5** [gaesa/mpv-hold-accelerate#1]
Hello, I am the author of a similar script [evafast](https://github.com/po5/evafast/tree/rewrite) which supports quality of life features you implemented like restoring the original playback speed, and does even more with a smooth speed ramp up, slowing down for upcoming subtitles, allows rewinding, has a toggle key, and allows seeking on the same key for fast keypresses.

I believe functionality of yours can already be replicated in evafast with this config:
```
seek_distance=0
speed_increase=2.5
speed_decrease=2.5
speed_cap=2.5
```
while obviously still benefiting from the other features if you want them.

I wonder if there is anything else you think would be a good addition to such a script.

**Comment by gaesa** [comment]
Thank you for your feedback. When I initially wrote this program, I was not aware of your program, [ evafast ](https://github.com/po5/evafast).

Having reviewed it now, I appreciate its features, particularly the UI hints and smooth speed ramp up, which I’m considering incorporating into my own program. In my experience with `evafast`, I noticed that the speed indicator is constantly updating during the smooth speed switch. Personally, I prefer a more minimalistic approach where this information is hidden during the transition. Additionally, I feel that the transition time for the smooth speed switch could be reduced, and the configuration options could be clearer. Of course, these are just my personal preferences.

My program places equal emphasis on both temporary speedup and slowdown, a feature I didn’t find in `evafast`. Perhaps I missed something? Additionally, with a focus on simplicity and user-friendliness, especially for beginners, I chose not to bind the temporary speedup to the right arrow key by default.

As a newcomer in this field, I developed this program as part of my learning journey. It is simpler and rougher compared to `evafast`, and lacks certain features like configuration options and smooth speed ramp up, I now realize that the smooth speed ramp up feature is useful to avoid stuck frames when the player returns to its original speed, something I wasn’t aware of before. Thank you for bringing your excellent project to my attention.

**Comment by po5** [comment]
My reasoning for not constantly displaying the time is that it gets in the way, especially when toggled or holding down the key for a while. It only shows up when the speed changes. I guess it'd be nice to add an option for always-on speed display.

I was using [fastforward.lua](https://github.com/jgreco/mpv-scripts/blob/master/fastforward.lua) before making my own script, so that's where the smooth transition idea came from. I was mainly bothered by how it shadowed my right arrow key for its fast-forward action, and I didn't want to waste an extra key on my keyboard for regular seeking. This is why in evafast by default the key is a hybrid, a quick press will seek and a long press will fast-forward without seeking. This idea comes from bilibili.com's web player.  
I believe I configured the default transition speed to be similar to fastforward.lua, but looking at the values it seems like evafast is by default half as fast.

Having different forwards speeds is currently supported but not very practical, you'd need a keybind that does `change-list script-opts append evafast-speed_cap=0.5`, and a keybind to change it back. Both separate from the evafast key.

I wish that something like the following would work, but complex keybindings don't work when multiple commands are bound to the same key:
```
LEFT change-list script-opts append evafast-speed_cap=0.5; script-binding evafast
RIGHT change-list script-opts append evafast-speed_cap=2; script-binding evafast
```
All events get reported as `press`. I don't have many ideas to make it better while keeping it configurable at runtime, keybinds don't take arguments so the only way I can see this maybe working is making the script listen to all events (I think that's possible), and having the user set their keybind to `script-binding evafast-0.5`, `script-binding evafast-2.0`... which we forward to the correct keybind function with our added ad-hoc parameter.

The reason I want non-default speeds to be a parameter for keybinds and not be included ahead of time in the config file is because I want to support an arbitrary number of different values, where both the config and the code to handle it would quickly spiral out of control.  
That's the feature I haven't been able to come up with an elegant solution for, maybe you can solve it.

I've also tried to implement skipping or increasing speed during silence, but values from ffmpeg's `silencedetect` filter jump around too much for me to make anything reliable out of it. This seems to be an issue with other scripts that use it: [mpv-skipsilence](https://github.com/ferreum/mpv-skipsilence), [silence-speed](https://github.com/aidangoettsch/mpv-silence-speed/blob/main/silence-speed.lua), [lilskippa](https://github.com/AN3223/dotfiles/blob/master/.config/mpv/scripts/lilskippa.lua). I haven't found a way to make it as pleasant as NewPipe's silence skipping feature, which is what I was aiming for. Again, if you know how to improve it :^)

A feature of evafast I don't advertise because it's for a very niche use case, is the ability to speed up towards a target time.  
`KEY_HERE script-message-to evafast speedup-target +5` will fast-forward for 5 seconds. `+` is a relative time, no sign is an absolute time e.g. `120` fast-forwards until it reaches the 2 minutes mark in the file, `-` is relative to the end time e.g. `-10` on a 2 minute file will fast-forward until 1:50.  
This feature is used by [groupwatch_sync](https://github.com/po5/groupwatch_sync) to smoothly reach the position of other users watching the same file as you. The script already comes with its own primitive speed adjustments, but when evafast is installed it can leverage all of its quality of life features with inter-script communication.

**Comment by gaesa** [comment]
Thank you for your detailed feedback and for introducing me to your script, `evafast`. I appreciate the time you’ve taken to explain its features and functionality. Here’s my understanding and response to the points you’ve raised:

1. **Always-On Speed Display**: I agree, adding an option for this in your script would be beneficial.

2. **Key Usage**: I understand the value of your hybrid key approach, where a quick press seeks and a long press fast-forwards. However, in my script, I’ve chosen to use separate keys for different functions to ensure predictability and to avoid potential uncontrollable behavior.

3. **Transition Speed**: I concur that adjusting the default transition speed could enhance the user experience.

4. **Support for Slowdown**: Your script supports different forward speeds, but it appears not to be very user-friendly. Perhaps this case wasn't considered initially, leading to the current situation. In contrast, my script treats speedup and slowdown equally from the outset, using the same high-level function to generate the target function.

5. **Change Temporary Speed at Runtime**: While the idea of monitoring all key events is valid, I believe it might be overkill for the use case of temporarily changing the speed of playback. This approach would require users to use extra keys to set the speed and a method to get the input. Then, users could use keys like `RIGHT` to temporarily change the speed to a specified value. However, this seems too complex, and all these modifications would be lost after users quit mpv. Therefore, I don't think it's worth implementing.

6. **Silent Transition**: I’m considering implementing this feature in my script. It could improve the user experience by making the speed changes less noticeable. Since I currently don't use the scripts you mentioned, and my codebase is relatively small, this feature may be implemented without much trouble.

7. **Speed Up Towards a Target Time**: The ability to fast-forward or rewind to a specific time point in the video is powerful IMHO. Also, the design of using negative values relative to the end time is quite ingenious. With this feature, users wouldn't have to rely on moving the mouse and clicking the timeline to jump to the desired time point. If mpv provides a mechanism to allow users to send input values at runtime to the script, similar to the `vim.ui.input()` in neovim, this could be extremely powerful.

I appreciate your openness to discussion and your willingness to share your knowledge.
